### PR TITLE
Integrate list / regexp dependencies, add autoloads and reformat

### PR DESCRIPTION
**Pull request by jasonm23**
- Removed the dependency on el-kit updated readme.
- Updated the dependency on `copy-list` from `cl.el` (now `cl-copy-list` `cl-lib`)
- Add the dependency requirement for `cl-lib` on compile.
- Add autoload for several functions.

### CODE REVIEW

**Comment by jasonm23** [comment]
I realised there's a couple things I need to do to make the package ELPA/MELPA compliant

**Comment by jasonm23** [comment]
Ready for review

**Comment by jasonm23** [comment]
Had to force push / broke tabs in last commit.  (use a squash before merge to drop superfluous commits)

**Comment by medikoo** [comment]
@jasonm23 thanks for that. Just few questions before I merge. Why is it problematic to have `el-kit` dependency. Wouldn't it be possible to have `el-kit` also on ELPA, and then add `el-ident`, so it installs with `el-kit` automatically?
Sorry if my questions are strange, but it's a while I didn't work with ELPA, and that's not clear to me.

What I feel is not right, is that I have some generic utils copied and pasted here, and now they need to be maintained in both `el-kit` and `el-ident`, that doesn't seem wise from maintanance perspective

**Comment by jasonm23** [comment]
My action there was driven by a suspicion that dash and other libraries will overlap el-kit.

I think it's better if we use standard or defacto libraries instead.

I will have a look and post my thoughts and findings later.

**Comment by medikoo** [comment]
@jasonm23 sure if there's something else that already serves purpose of el-kit and evolves, then such point makes sense

**Comment by jasonm23** [comment]
It looks like dash.el `-replace` will do what `el-kit-lisp-replace` does (the params are in a different order) 

However I'm coming up blank on the regexp group function.  I think the expression itself is pretty trivial, but you should decide if this presents an unreasonable maintenance issue if it were to be inlined into `el-indent-convert-rules`.

**Comment by medikoo** [comment]
I'm fine with using dash.el and leaving regexp group as you proposed. Still what about `el-indent-list-index-of` ?

**Comment by jasonm23** [comment]
On mobile now, but I think that index-of is a dependency of replace, and not used directly.

I'll double check shortly.

**Comment by jasonm23** [comment]
Hi just a note, I can't seem to find el-kit anymore at all, do you know where it is?

**Comment by jasonm23** [comment]
Ok no worries found. https://github.com/medikoo/el-kit

**Pull request closed without merging**
